In [ ]:
import numpy as np
import torch

# Lab01 : Tensor Manipulation

## Array with PyTorch

In [ ]:
# 1D
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[-1])
print(t[:3], t[3:-1])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(6.)
tensor([0., 1., 2.]) tensor([3., 4., 5.])


In [ ]:
# 2D
t = torch.FloatTensor([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(t)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[:, 1])  # [ 행 : 열 ]
print(t[:, 2])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 1.,  4.,  7., 10.])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 0.,  1.],
        [ 3.,  4.],
        [ 6.,  7.],
        [ 9., 10.]])


## Broadcasting

- 자동으로 실행되기 때문에 주의해줘야 함.
- 생각했던 계산이 아님에도 오류없이 진행되기 때문에 나중에 문제 발생 시 어디서 잘못됐는지 찾기 어려움

In [ ]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)  # [[1, 2]] + [[3, 3]]

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)  # [[1, 2], [1, 2]] + [[3, 3], [4, 4]]

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [ ]:
# matmul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shaoe of Matrix m1 :", m1.shape) # 2 x 2
print("Shaoe of Matrix m2 :", m2.shape) # 2 x 1
print(m1.matmul(m2)) # => 2 x 1

Shaoe of Matrix m1 : torch.Size([2, 2])
Shaoe of Matrix m2 : torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# mul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shaoe of Matrix m1 :", m1.shape) # 2 x 2
print("Shaoe of Matrix m2 :", m2.shape) # 2 x 1
print(m1 * m2)
print(m1.mul(m2)) # => 2 x 2

Shaoe of Matrix m1 : torch.Size([2, 2])
Shaoe of Matrix m2 : torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

- 원하는 차원만 지정해서 평균 추출 가능

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.LongTensor([1, 2])

try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


> dim = 0 : **세로 방향**으로 계산

> dim = 1 : **가로 방향**으로 계산


## Max and Argmax

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])

print(t.max(dim=0), "\n") # max와 argmax 두가지 값 반환
print("Max :", t.max(dim=0)[0])
print("Argmax :", t.max(dim=0)[1])

print("")
print("Max :", t.max(dim=1)[0])
print("Argmax :", t.max(dim=1)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1])) 

Max : tensor([3., 4.])
Argmax : tensor([1, 1])

Max : tensor([2., 4.])
Argmax : tensor([1, 1])


## View(Reshape)



```
|tt| =  (2, 2, 3)               2 x 2 x 3 = 12
     => (2x2, 3) = (4, 3)       4 x 3 = 12
     => (2x2, 1, 3) = (4, 1, 3) 4 x 1 x 3 = 12
```



In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8,],
               [9, 10, 11]]])

tt = torch.FloatTensor(t)
print(tt.shape)

torch.Size([2, 2, 3])


In [ ]:
print(tt.view([-1, 3]))
print(tt.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
print(tt.view([-1, 1, 3]))
print(tt.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze & Unsqueexe

- 사이즈가 1인 차원을 없애줌 & 차원을 늘려줌

In [ ]:
# squeeze
t = torch.FloatTensor([[0], [1], [2]])

print(t)
print(t.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(t.squeeze())
print(t.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# unsqueeze
t = torch.FloatTensor([0, 1, 2])
print(t.shape)

torch.Size([3])


In [ ]:
print(t.unsqueeze(0))
print(t.unsqueeze(0).shape) # |t| = (3, ) -> (1, 3)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(t.view(1, -1))
print(t.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(t.unsqueeze(1))
print(t.unsqueeze(1).shape) # |t| = (3, ) -> (3, 1)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

- Type 변환

In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


```
bt = (lt == 3 )  ==>  bt = [0, 0, 1, 0]
```

## Concatenate

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [ ]:
x = torch.FloatTensor([1, 2])
y = torch.FloatTensor([3, 4])
z = torch.FloatTensor([5, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


## Ones and Zeros

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

- 새로운 저장공간 생성하는 대신 존재하던 변수에 뒤덮음으로써 저장공간 낭비 방지

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
print(x.mul(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# Lab02 : Linear regresssion

In [ ]:
# 학습 데이터 선언
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
# 초기의 가중치와 편향 설정 -> 주로 0으로 두고 학습 시작
W = torch.zeros(1, requires_grad=True) # requires_grad=True : 학습할 변수임을 명시
b = torch.zeros(1, requires_grad=True)

In [ ]:
# 옵티마이저 정의 -> SGD 선언
optimizer = torch.optim.SGD([W, b], lr=0.01)

In [ ]:
# 학습 진행
nb_epochs = 1000
for epoch in range(1, nb_epochs+1):
    # 가설 설정
    hypothesis = W * X_train + b
    # 손실함수 설정 -> 선형 회귀는 주로 MSE 많이 사용
    cost = torch.mean((hypothesis - y_train) ** 2)
    # SGD 선언
    optimizer.zero_grad() # gradient를 0으로 초기화
    cost.backward()       # gradient 계산
    optimizer.step()      # Gradient Descent를 진행하여 W와 b를 개선

In [ ]:
print(hypothesis) # 예측값 저장되어 있음
print(cost) # 오차 0.0006

tensor([[2.0373],
        [4.0080],
        [5.9787]], grad_fn=<AddBackward0>)
tensor(0.0006, grad_fn=<MeanBackward0>)


# Lab03 : Gradient Descent

## 1) SGD 수식으로 풀이

In [ ]:
# 학습 데이터
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# 가중치 초기화
W = torch.zeros(1)

# learning rate 설정
lr = 0.1

# 학습 진행
nb_epochs = 10
for epoch in range(1, nb_epochs+1):
    # 가설 설정,  H(x) 계산
    hypothesis = W * X_train

    # 손실함수와 옵티마이저 설정 -> 선형 회귀는 손실함수로 MSE 많이 사용
    cost = torch.mean((hypothesis - y_train) ** 2)
    gradient = torch.sum((W * X_train - y_train) * X_train)

    print("Epoch {:4d}/{} W : {:.3f}, Cost: {:.6f}".format(
        epoch, nb_epochs, W.item(), cost.item()))

    # cost gradient로 H(x) 개선
    W -= lr * gradient

Epoch    1/10 W : 0.000, Cost: 4.666667
Epoch    2/10 W : 1.400, Cost: 0.746666
Epoch    3/10 W : 0.840, Cost: 0.119467
Epoch    4/10 W : 1.064, Cost: 0.019115
Epoch    5/10 W : 0.974, Cost: 0.003058
Epoch    6/10 W : 1.010, Cost: 0.000489
Epoch    7/10 W : 0.996, Cost: 0.000078
Epoch    8/10 W : 1.002, Cost: 0.000013
Epoch    9/10 W : 0.999, Cost: 0.000002
Epoch   10/10 W : 1.000, Cost: 0.000000


## 2) torch 내장 함수로 풀이

In [ ]:
# 학습 데이터
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# 가중치 초기화
W = torch.zeros(1, requires_grad=True)

# 옵티마이저 정의 -> SGD 선언
optimizer = torch.optim.SGD([W], lr=0.1)

# 학습 진행
nb_epochs = 10
for epoch in range(1, nb_epochs+1):
    # 가설 설정,  H(x) 계산
    hypothesis = W * X_train

    # 손실함수 설정 -> 선형 회귀는 손실함수로 MSE 많이 사용
    cost = torch.mean((hypothesis - y_train) ** 2)

    print("Epoch {:4d}/{} W : {:.3f}, Cost: {:.6f}".format(
        epoch, nb_epochs, W.item(), cost.item()))

    # cost gradient로 H(x) 개선
    optimizer.zero_grad() # gradient를 0으로 초기화
    cost.backward()       # gradient 계산
    optimizer.step()      # Gradient Descent를 진행하여 W와 b를 개선

Epoch    1/10 W : 0.000, Cost: 4.666667
Epoch    2/10 W : 0.933, Cost: 0.020741
Epoch    3/10 W : 0.996, Cost: 0.000092
Epoch    4/10 W : 1.000, Cost: 0.000000
Epoch    5/10 W : 1.000, Cost: 0.000000
Epoch    6/10 W : 1.000, Cost: 0.000000
Epoch    7/10 W : 1.000, Cost: 0.000000
Epoch    8/10 W : 1.000, Cost: 0.000000
Epoch    9/10 W : 1.000, Cost: 0.000000
Epoch   10/10 W : 1.000, Cost: 0.000000


In [ ]:
print(hypothesis)
print(cost)

tensor([[1.],
        [2.],
        [3.]], grad_fn=<MulBackward0>)
tensor(0., grad_fn=<MeanBackward0>)
