# Convolution 연산 연습

In [ ]:
import torch
import torch.nn as nn

## conv2d

    torch.nn.Conv2d(in_channels, out_channels,
                    kernel_size, stride=n, padding=0, bais=True,..)

In [ ]:
from math import floor
def output_size(input_size, fiter_size, padding, stride):
    return floor((input_size - fiter_size + 2*padding)/stride) + 1

In [ ]:
# padding X
conv = nn.Conv2d(1, 1, 11, stride=4, padding=0)
conv

Conv2d(1, 1, kernel_size=(11, 11), stride=(4, 4))

In [ ]:
input = torch.Tensor(1, 1, 227, 227)
print(input.shape)
input

torch.Size([1, 1, 227, 227])


tensor([[[[ 3.9447e-42,  0.0000e+00,         nan,  ...,         nan,
                   nan,         nan],
          [ 8.3695e-36,  6.2601e-37,         nan,  ...,  9.8154e-37,
            2.5759e-33,         nan],
          [        nan,         nan,  4.0445e-33,  ...,  3.5265e-37,
                   nan,         nan],
          ...,
          [ 8.0465e-27,  4.5265e-41, -3.2199e-10,  ...,  3.4159e+18,
            1.8220e-34,  6.8064e-27],
          [ 4.5265e-41,  6.8069e-27,  4.5265e-41,  ...,  4.5265e-41,
            4.7240e-05,  9.4473e+27],
          [ 2.3892e-29,  4.5265e-41,  2.3870e-29,  ...,  2.4652e-29,
            4.5265e-41,  6.9383e+18]]]])

In [ ]:
out = conv(input)
print('output_size :', output_size(227, 11, 0, 4))
print(out.shape)
out

output_size : 55
torch.Size([1, 1, 55, 55])


tensor([[[[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [ 8.5343e+35, -2.3015e+36,  4.2844e+35,  ..., -1.0536e+37,
           -4.2705e+34,  5.3196e+34],
          [-5.8759e+35, -8.2770e+35, -3.0231e+36,  ...,  1.4136e+36,
           -4.2745e+35, -1.7236e+34],
          [ 1.2382e+33,  7.4133e+32, -1.4688e+36,  ..., -8.3549e+35,
            9.4502e+35,  6.1695e+33]]]], grad_fn=<ConvolutionBackward0>)

In [ ]:
# Padding O
conv = nn.Conv2d(1, 1, 3, stride=1, padding=2)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2))

In [ ]:
input = torch.Tensor(1, 1, 64, 32)
print(input.shape)
input

torch.Size([1, 1, 64, 32])


tensor([[[[3.3631e-44, 0.0000e+00, 2.9903e+14,  ..., 4.5265e-41,
           1.4013e-45, 7.0065e-45],
          [1.4013e-45, 1.1210e-44, 1.4013e-45,  ..., 4.5265e-41,
           2.7955e+14, 4.5265e-41],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 4.3440e-44,
           1.4013e-45, 4.6243e-44],
          ...,
          [5.1492e+31, 1.6533e+19, 7.0062e+22,  ..., 3.8473e+03,
           4.7427e+30, 4.4598e+30],
          [1.4607e-19, 4.7697e+33, 1.8337e+31,  ..., 3.2314e-18,
           1.7000e+08, 1.1866e+27],
          [7.5839e+31, 1.8990e+28, 4.7987e+30,  ..., 3.1378e-41,
           6.6012e+19, 3.1378e-41]]]])

In [ ]:
out = conv(input)
print('output_size :', output_size(64, 3, 2, 1),  output_size(32, 3,2, 1))
print(out.shape)
out

output_size : 66 34
torch.Size([1, 1, 66, 34])


tensor([[[[-2.3518e-01, -2.3518e-01,  1.7940e+13,  ..., -2.3518e-01,
           -2.3518e-01, -2.3518e-01],
          [-2.3518e-01, -2.3518e-01,  4.1223e+13,  ..., -5.1669e+12,
            2.9295e+13, -2.3518e-01],
          [-2.3518e-01, -2.3518e-01, -5.8786e+13,  ..., -6.6028e+12,
           -6.0726e+13, -2.3518e-01],
          ...,
          [-5.5728e+30,  6.7134e+32, -9.3535e+31,  ...,  5.2475e+29,
            2.0874e+30,  7.2354e+29],
          [ 1.0455e+31, -9.3945e+32,  1.3899e+33,  ..., -2.3328e+26,
            3.5062e+26,  1.9258e+26],
          [-1.4909e+31,  2.2404e+31,  1.1370e+31,  ...,  1.9504e+19,
            1.0713e+19, -2.3518e-01]]]], grad_fn=<ConvolutionBackward0>)

## MaxPool2d

    porch.nn.MaxPool2d(kernel_size, stride=None,
                       padding=0, dilation=1, return_indices=False,
                       cell_mode=False)

In [ ]:
input = torch.Tensor(1, 1, 28, 28)

# input_size=1, output_size=5, fiter_size=5, stride=1
conv = nn.Conv2d(1, 5, kernel_size=5, stride=1)
pool = nn.MaxPool2d(2) # 2x2내에서 max값 추출

out = conv(input)
out2 = pool(out)

print(out.size())
print(out2.size())

torch.Size([1, 5, 24, 24])
torch.Size([1, 5, 12, 12])


# MNIST로 CNN 실습

1. 라이브러리 불러오기
2. GPU 설정 및 random value를 위한 seed 설정
3. 학습에 사용되는 파라미터 설정(learning rate, epoch, batch size,..)
4. 데이터셋 가져오고 data loader 만들기
5. 학습 모델 생성
6. loss function와 optimizer 선택
7. 모델 학습 및 loss check
8. 학습된 모델 성능 확인

In [ ]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import torch.nn.init
from torch.utils.data import DataLoader

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

print(device)

cpu


In [ ]:
# parameters
learning_rate = 0.001
training_epochs = 10
batch_size = 100

In [ ]:
# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)
mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

In [ ]:
# data_lodaer
data_loader = DataLoader(dataset=mnist_train, batch_size=batch_size,
                         shuffle=True, drop_last=True)

In [ ]:
# model 생성
class CNN(nn.Module):

    def __init__(self):
        super(CNN, self).__init__() # 꼭 해줘야 학습이 된다고..!!!!

        self.layer1 = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.layer2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Linear(7*7*64, 10, bias=True)

        # 가중치 초기화
        torch.nn.init.xavier_uniform_(self.fc.weight)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out

In [ ]:
model = CNN().to(device)
model

CNN(
  (layer1): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Linear(in_features=3136, out_features=10, bias=True)
)

In [ ]:
model(torch.Tensor(1, 1, 228, 228).to(device)).shape

In [ ]:
# 손실함수 및 옵티마이저 생성
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
# training
total_batch = len(data_loader)

for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:
        X = X.to(device)
        Y = Y.to(device)

        optimizer.zero_grad() # 필수!!!
        hypothesis = model(X)

        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

    print('[Epoch:{}] cost = {}'.format(epoch+1, avg_cost))

print('Finished~~~~!')

[Epoch:1] cost = 0.22217074036598206
[Epoch:2] cost = 0.06470973044633865
[Epoch:3] cost = 0.047272197902202606
[Epoch:4] cost = 0.037742435932159424
[Epoch:5] cost = 0.03084304928779602
[Epoch:6] cost = 0.02637961320579052
[Epoch:7] cost = 0.02239801362156868
[Epoch:8] cost = 0.018839770928025246
[Epoch:9] cost = 0.0156009616330266
[Epoch:10] cost = 0.013950684107840061
Finished~~~~!


In [ ]:
# Test
with torch.no_grad(): # 학습 시키는 데이터가 아니라고 명시해 주는 것
    X_test = mnist_test.test_data.view(len(mnist_test), 1, 28, 28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)

    prediction = model(X_test)
    correct_prediction = torch.argmax(prediction, 1) == Y_test
    accuracy = correct_prediction.float().mean()

    print('Accuracy :', accuracy.item())

/usr/local/lib/python3.10/dist-packages/torchvision/datasets/mnist.py:80: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/usr/local/lib/python3.10/dist-packages/torchvision/datasets/mnist.py:70: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


Accuracy : 0.9858999848365784


# Visdom

In [ ]:
visdom은 colab에서 시용 불가 흑흑 ㅠ

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils, datasets

! pip install tensorboardcolab
from tensorboardcolab import TensorBoardColab

In [ ]:
class Network(nn.Module):
  def __init__(self):
    super(Network, self).__init__()
    self.conv1 = nn.Conv2d(1, 20, 5, 1)
    self.conv2 = nn.Conv2d(20, 50, 5, 1)
    self.fc1 = nn.Linear(4*4*50, 500)
    self.fc2 = nn.Linear(500, 10)

  def forward(self, x):
    x = F.relu(self.conv1(x))
    x = F.max_pool2d(x, 2, 2)
    x = F.relu(self.conv2(x))
    x = F.max_pool2d(x, 2, 2)
    x = x.view(-1, 4*4*50)
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return F.log_softmax(x, dim=1)

In [ ]:
class Config:
  def __init__(self, **kwargs):
    for key, value in kwargs.items():
      setattr(self, key, value)


model_config = Config(
    cuda = True if torch.cuda.is_available() else False,
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    seed = 2,
    lr = 0.01,
    epochs = 4,
    save_model = False,
    batch_size = 32,
    log_interval = 100
)

class Trainer:

  def __init__(self, config):

    self.cuda = config.cuda
    self.device = config.device
    self.seed = config.seed
    self.lr = config.lr
    self.epochs = config.epochs
    self.save_model = config.save_model
    self.batch_size = config.batch_size
    self.log_interval = config.log_interval

    self.globaliter = 0
    self.tb = TensorBoardColab()

    torch.manual_seed(self.seed)

    kwargs = {'num_workers': 1, 'pin_memory': True} if self.cuda else {}

    self.train_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=True, download=True,
                     transform=transforms.Compose([
                         transforms.ToTensor(),
                         transforms.Normalize((MNIST_MEAN,), (MNIST_STD,))
                     ])),
        batch_size=self.batch_size, shuffle=True, **kwargs)

    self.test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=False, transform=transforms.Compose([
                             transforms.ToTensor(),
                             transforms.Normalize((MNIST_MEAN,), (MNIST_STD,))
                         ])),
        batch_size=self.batch_size, shuffle=True, **kwargs)


    self.model = Network().to(self.device)
    self.optimizer = optim.Adam(self.model.parameters(), lr=self.lr)


  def train(self, epoch):

    self.model.train()
    for batch_idx, (data, target) in enumerate(self.train_loader):

      self.globaliter += 1
      data, target = data.to(self.device), target.to(self.device)

      self.optimizer.zero_grad()
      predictions = self.model(data)

      loss = F.nll_loss(predictions, target)
      loss.backward()
      self.optimizer.step()

      if batch_idx % self.log_interval == 0:
        print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                  epoch, batch_idx * len(data), len(self.train_loader.dataset),
                  100. * batch_idx / len(self.train_loader), loss.item()))
        self.tb.save_value('Train Loss', 'train_loss', self.globaliter, loss.item())


  def test(self, epoch):
    self.model.eval()
    test_loss = 0
    correct = 0

    with torch.no_grad():
      for data, target in self.test_loader:
        data, target = data.to(self.device), target.to(self.device)
        predictions = self.model(data)

        test_loss += F.nll_loss(predictions, target, reduction='sum').item()
        prediction = predictions.argmax(dim=1, keepdim=True)
        correct += prediction.eq(target.view_as(prediction)).sum().item()

      test_loss /= len(self.test_loader.dataset)
      accuracy = 100. * correct / len(self.test_loader.dataset)

      print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
          test_loss, correct, len(self.test_loader.dataset), accuracy))


def main():

  trainer = Trainer(model_config)

  for epoch in range(1, trainer.epochs + 1):
      trainer.train(epoch)
      trainer.test(epoch)
      trainer.tb.flush_line('train_loss')

  if (trainer.save_model):
      torch.save(trainer.model.state_dict(),"mnist_cnn.pt")

In [ ]:
main()

ERROR:websocket:[Errno 99] Cannot assign requested address - goodbye
ERROR:websocket:error from callback <function Visdom.setup_socket.<locals>.on_close at 0x7e2d66f01cf0>: Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given
ERROR:visdom:Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given
ERROR:visdom:[Errno 99] Cannot assign requested address
ERROR:websocket:[Errno 99] Cannot assign requested address - goodbye
ERROR:websocket:error from callback <function Visdom.setup_socket.<locals>.on_close at 0x7e2d66f02950>: Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given
ERROR:visdom:Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given

KeyboardInterrupt



Wait for 8 seconds...


ERROR:visdom:[Errno 99] Cannot assign requested address
ERROR:websocket:[Errno 99] Cannot assign requested address - goodbye
ERROR:websocket:error from callback <function Visdom.setup_socket.<locals>.on_close at 0x7e2d66f01cf0>: Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given
ERROR:visdom:Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given
ERROR:visdom:[Errno 99] Cannot assign requested address
ERROR:websocket:[Errno 99] Cannot assign requested address - goodbye
ERROR:websocket:error from callback <function Visdom.setup_socket.<locals>.on_close at 0x7e2d66f02950>: Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given
ERROR:visdom:Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given


KeyboardInterrupt: ignored